kind: ConfigMap
apiVersion: v1
data:
  hello: {{ .HELLO_MSG }}
  s3cfg: |-
    [default]
    access_key = {{ .S3_USER }}
    secret_key = {{ .S3_PASSWORD }}
    host_base = {{ .S3_URL }}
    host_bucket =
    signature_v2 = False
    use_https = {{ .S3_HTTPS }}

