kind: Secret
apiVersion: v1
metadata:
  name: crdb-{{ .Values.set_name }}-{{ .Values.env_name }}-password
  labels:
    setname: crdb-{{ .Values.set_name }}-{{ .Values.env_name }}
stringData:
  crdb-{{ .Values.set_name }}-{{ .Values.env_name }}-password: "{{ .Values.ocockroachpassword }}"

